### PR TITLE
[fix #346] upgrade python module 'six' in travis-ci

### LINKED ISSUE #346: import error in travis-ci
STDERR:
Traceback (most recent call last):
  File "./app.py", line 9, in <module>
    from iota_cache.iota_cache import IotaCache
  File "../iota_cache/iota_cache.py", line 5, in <module>
    from iota import Iota, Address, ProposedTransaction, Tag, Transaction, TryteString, TransactionTrytes, ProposedBundle, Nonce, BundleHash,TransactionHash, Fragment
  File "/usr/local/lib/python2.7/dist-packages/iota/__init__.py", line 35, in <module>
    from .types import *
  File "/usr/local/lib/python2.7/dist-packages/iota/types.py", line 13, in <module>
    from six import PY2, binary_type, itervalues, python_2_unicode_compatible, \
ImportError: cannot import name python_2_unicode_compatible

### PR DESCRIPTION
**Pull request by lhfbc**

### CODE REVIEW

**Comment by lhfbc** [comment]
[import error](https://stackoverflow.com/questions/20741754/python-2-unicode-compatible-error/20746761)

**Comment by stplaydog** [comment]
cmdOpt =--testnet --snapshot=./Snapshot.txt --mwm 1 --walk-validator "NULL" --ledger-validator "NULL" --max-peers 40 --remote --enable-streaming-graph --entrypoint-selector-algorithm "KATZ" --tip-sel-algo "CONFLUX"
start python script..
Exception in thread background thread for pid 9108:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 
  RAN: /usr/bin/python ./app.py
  STDOUT:
  STDERR:
Traceback (most recent call last):
  File "./app.py", line 9, in <module>
    from iota_cache.iota_cache import IotaCache
  File "../iota_cache/iota_cache.py", line 5, in <module>
    from iota import Iota, Address, ProposedTransaction, Tag, Transaction, TryteString, TransactionTrytes, ProposedBundle, Nonce, BundleHash,TransactionHash, Fragment
  File "/usr/local/lib/python2.7/dist-packages/iota/__init__.py", line 35, in <module>
    from .types import *
  File "/usr/local/lib/python2.7/dist-packages/iota/types.py", line 13, in <module>
    from six import PY2, binary_type, itervalues, python_2_unicode_compatible, \
ImportError: cannot import name python_2_unicode_compatible
start cli: enable_ipfs 1, enable_batch 0, enable_compression 0
current tx count is 0
start put_file...
Send command failed  0
The command "bash run_all_stable_tests.sh $VERSION" exited with 255.

**Review by stplaydog — APPROVED** [review]
Please paste the web page with correct solutions.
We owe more technical debts now.....

**Comment by lhfbc** [comment]
> Please paste the web page with correct solutions.
> We owe more technical debts now.....

[upgrade six module](https://stackoverflow.com/questions/31417964/importerror-cannot-import-name-wraps)

**Pull request merged**
